In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
# creates a 1D array

In [3]:
print('x = ', x)

x =  [1 2 3 4 5]


In [4]:
x.ndim
# It returns the number of array dimensions.

1

In [8]:
# 2-D array
Y = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
print(Y)
print(Y.ndim) 2D
print(Y.shape) # (4,3) or 4 by 3, in 2D

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [10]:
# Here the`zeros()` is an inbuilt function that you'll study on the next page. 
# The tuple (2, 3, 4( passed as an argument represents the shape of the ndarray
y = np.zeros((2,3,4))
print(y.ndim)
print(y)

3
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [17]:
print("x = ", x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [12]:
w = np.array(['Hello', 'World'])

In [13]:
print('w = ', w )
print('w has dimensions:', w.shape)
print('w is an object of type:', type(w)) 
print('The elements in w are of type:', w.dtype)

w =  ['Hello' 'World']
w has dimensions: (2,)
w is an object of type: <class 'numpy.ndarray'>
The elements in w are of type: <U5


In [14]:
m = np.array([1,2, 'World'])
print ('m = ', m)
print('m has dimensions:', m.shape)
print('m is an object of type:', type(m))
print('The elements in m are of type:', m.dtype)

m =  ['1' '2' 'World']
m has dimensions: (3,)
m is an object of type: <class 'numpy.ndarray'>
The elements in m are of type: <U21


In [15]:
i = np.array([1,2,3])
f = np.array([1.9,2.9,3.0])
z = np.array([1, 2.5, 4])
print('The elements in i are of type:', i.dtype)
print('The elements in f are of type:', f.dtype)
print('The elements in z are of type:', z.dtype)


The elements in i are of type: int64
The elements in f are of type: float64
The elements in z are of type: float64


In [16]:
r = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)
print('r = ', r)
print('The elements in r are of type:', r.dtype)


r =  [1 2 3 4 5]
The elements in r are of type: int64


In [17]:
t = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
print('t = \n', t)
print('t has dimensions:', t.shape)
print('t has a total of', t.size, 'elements')
print('t has an object of type:', type(t))
print('The elements in t are of type:', t.dtype)

t = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
t has dimensions: (4, 3)
t has a total of 12 elements
t has an object of type: <class 'numpy.ndarray'>
The elements in t are of type: int64


In [22]:
# Save the NumPy array to a File
np.save('my_array', t)

The above saves the t ndarray into a file named my_array.npy. You can load the saved ndarray into a variable by using the load() function.

In [23]:
lion = np.load('my_array.npy')

In [24]:
print(lion)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
print()
print('lion = ', lion)
print()

# We print information about the ndarray we loaded
print('lion is an object of type:', type(lion))
print('The elements in lion are of type:', lion.dtype)


lion =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

lion is an object of type: <class 'numpy.ndarray'>
The elements in lion are of type: int64
