We have reached the last lesson in this Introduction to NumPy. In this last lesson we will see how NumPy does arithmetic operations on ndarrays. NumPy allows element-wise operations on ndarrays as well as matrix operations. In this lesson we will only be looking at element-wise operations on ndarrays. In order to do element-wise operations, NumPy sometimes uses something called Broadcasting. Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. For example, broadcasting is used implicitly when doing arithmetic operations between scalars and ndarrays.

Let's start by doing element-wise addition, subtraction, multiplication, and division, between ndarrays. To do this, NumPy provides a functional approach, where we use functions such as np.add(), or by using arithmetic symbols, such as +, that resembles more how we write mathematical equations. Both forms will do the same operation, the only difference is that if you use the function approach, the functions usually have options that you can tweak using keywords. It is important to note that when performing element-wise operations, the shapes of the ndarrays being operated on, must have the same shape or be broadcastable. We'll explain more about this later in this lesson. Let's start by performing element-wise arithmetic operations on rank 1 ndarrays:

Example 1. Element-wise arithmetic operations on 1-D arrays

In [1]:
import numpy as np

In [2]:
# Example 1. Element-wise arithmetic operations on 1-D arrays

In [3]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])


In [4]:
# We print x
print()
print('x = ', x)


x =  [1 2 3 4]


In [5]:
# We print y
print()
print('y = ', y)
print()


y =  [5.5 6.5 7.5 8.5]



In [6]:
# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


We can also perform the same element-wise arithmetic operations on rank 2 ndarrays. Again, remember that in order to do these operations the shapes of the ndarrays being operated on, must have the same shape or be broadcastable.

Example 2. Element-wise arithmetic operations on a 2-D array (Same shape)

In [7]:
# Example 2. Element-wise arithmetic operations on a 2-D array (Same shape)

In [8]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

In [9]:
# We print X
print()
print('X = \n', X)


X = 
 [[1 2]
 [3 4]]


In [10]:
# We print Y
print()
print('Y = \n', Y)
print()


Y = 
 [[5.5 6.5]
 [7.5 8.5]]



In [11]:
# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


We can also apply mathematical functions, such as sqrt(x), to all elements of an ndarray at once.

Example 3. Additional mathematical functions

In [12]:
# Example 3. Additional mathematical functions
# np.exp() calculates e^x for each x in your list/array, where e is Euler's number (approximately 2.718281)

# The exponential function is e^x where e is a mathematical constant called
# Euler's number, approximately 2.718281. This value has a close mathematical relationship 
# with pi and the slope of the curve e^x is equal to 
# its value at every point. np.exp() calculates e^x for each value of x in your input array.

In [13]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4])

In [14]:
# We print x
print()
print('x = ', x)


x =  [1 2 3 4]


In [15]:
# We apply different mathematical functions to ALL elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2


EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]


Another great feature of NumPy is that it has a wide variety of statistical functions. Statistical functions provide us with statistical information about the elements in an ndarray.

Note - Most of the statistical operations can be done using either a function or an equivalent method. For example, both numpy.mean function and numpy.ndarray.mean method will return the arithmetic mean of the array elements along the given axis.
Let's see some examples showing a variety of statistical operations:

Example 4. Statistical functions

In [16]:
# Example 4. Statistical functions

In [17]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

In [18]:
# We print x
print()
print('X = \n', X)
print()



X = 
 [[1 2]
 [3 4]]



In [19]:
#CLARIFYING AMBIGUITY IN PANDAS DATAFRAME / NUMPY ARRAY "AXIS" DEFINITIONS
#IN NUMPY THIS IS IMPORTANT WHEN PREFORMING OPERTIONS SUCH AS
# SORTING AND NUMERICAL CALCULATIONS ACROSS THE DATA

#It's perhaps simplest to remember it as 0=down and 1=across.

#This means:

#Use axis=0 to apply a method down each column, or to the row labels (the index).
#Use axis=1 to apply a method across each row, or to the column labels.

#-----

#If axis = 0 is specified for a given 2-D array - 
# For one column at a time, the function will sort all rows, without disturbing other elements. 
# In the final output, you will see that each column has been sorted individually.

#The output of axis = 1 for a given 2-D array is vice-versa for axis = 0. 
#In the final output, you will see that each row has been sorted individually.

# Tip: As mentioned in this discussion, 
# you can read axis = 0 as "down" and 
# axis = 1 as "across" the given 2-D array, 
# to have a correct usage of axis in your methods/functions.

In [20]:
print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


Finally, let's see how NumPy can add single numbers to all the elements of an ndarray without the use of complicated loops.

Example 5. Change value of all elements of an array

In [21]:
# Example 5. Change value of all elements of an array

In [22]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

In [23]:
# We print x
print()
print('X = \n', X)
print()


X = 
 [[1 2]
 [3 4]]



In [24]:
print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]


In the examples above, NumPy is working behind the scenes to broadcast 3 along the ndarray so that they have the same shape. This allows us to add 3 to each element of X with just one line of code.

Subject to certain constraints, Numpy can do the same for two ndarrays of different shapes, as we can see below.

Example 6. Arithmetic operations on 2-D arrays (Compatible shape)

In [25]:
# Example 6. Arithmetic operations on 2-D arrays (Compatible shape)

In [26]:
# We create a rank 1 ndarray
x = np.array([1,2,3])

In [27]:
# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

In [29]:
# We print x
print()
print('x = ', x)
print()


x =  [1 2 3]



In [30]:
# We print Y
print()
print('Y = \n', Y)
print()


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



In [31]:
# We print Z
print()
print('Z = \n', Z)
print()


Z = 
 [[1]
 [2]
 [3]]



In [32]:
# Broadcasting the x arrary across Y
print('x + Y = \n', x + Y)
print()
# Broadcasting the Z arrary across Y
print('Z + Y = \n',Z + Y)

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


As before, NumPy is able to add 1 x 3 and 3 x 1 ndarrays to 3 x 3 ndarrays by broadcasting the smaller ndarrays along the big ndarray so that they have compatible shapes. In general, NumPy can do this provided that the smaller ndarray, such as the 1 x 3 ndarray in our example, can be expanded to the shape of the larger ndarray in such a way that the resulting broadcast is unambiguous.

Make sure you check out the NumPy Documentation for more information on Broadcasting and its rules: https://numpy.org/devdocs/user/basics.broadcasting.html

Glossary of Mathematical Functions
Refer to this list of NumPy Mathematical Functions to find the one you need.
https://numpy.org/devdocs/reference/routines.math.html?highlight=arithmetic#mathematical-functions

In [33]:
# broadcasting the smaller ndarrays along the big ndarray so that they have compatible shapes.
# In general, NumPy can do this provided that the smaller ndarray, 
# such as the 1 x 3 ndarray in our example, can be expanded to the shape of the larger ndarray
# in such a way that the resulting broadcast is unambiguous.

In [34]:
#QUIZ 

In [35]:
# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

# Do not change the name of this array. 
# Please don't print anything from your code! The TEST RUN button below will print your array. 
X = np.ones((4,4)) + np.array([0,1,2,3])



In [36]:
#OR 

In [37]:
# We will make use of array multiplication, as demonstrated on the previous page:
# "Example 6. Arithmetic operations on 2-D arrays (Compatible shape)"


# np.ones((4,4)) will give you a 4 x 4 matrix
#[[1. 1. 1. 1.],
# [1. 1. 1. 1.],
# [1. 1. 1. 1.],
# [1. 1. 1. 1.]]

# np.arange(1,5) will give you a 1 x 4 matrix
# [1 2 3 4]

# X can be calculated by multiplying the above two matrices, as shown below, to get:
#[[1. 2. 3. 4.],
# [1. 2. 3. 4.],
# [1. 2. 3. 4.],
# [1. 2. 3. 4.]]
X = np.ones((4,4)) * np.arange(1,5)