In [1]:
import numpy as np

In [2]:
# creates a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4))

In [3]:
print('X = \n', X)


X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [5]:
# creates a 3 x 2 ndarray full of ones.
X1 = np.ones((3,2))

In [6]:
print('X1 = \n', X1)

X1 = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
print('X1 has dimensions:', X1.shape)
print('X1 is an object of type:', type(X1))
print('The elements in X1 are of type:', X1.dtype) 


X1 has dimensions: (3, 2)
X1 is an object of type: <class 'numpy.ndarray'>
The elements in X1 are of type: float64


In [7]:
# create a 2 x 3 ndarray full of fives. 5 is the 'constant'
X3 = np.full((2,3), 5) 

In [8]:
print('X3 = \n', X3)

X3 = 
 [[5 5 5]
 [5 5 5]]


In [9]:
print('X3 has dimensions:', X3.shape)
print('X3 is an object of type:', type(X3))
print('The elements in X3 are of type:', X3.dtype)

X3 has dimensions: (2, 3)
X3 is an object of type: <class 'numpy.ndarray'>
The elements in X3 are of type: int64


In [10]:
# We create a 5 x 5 Identity matrix. 
# the identity matrix is the infamous matrix that includes 'matching values' in a diagonal line across the matrix
X4 = np.eye(5)

In [11]:
print('X4 = \n', X4)

X4 = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [42]:
print('X4 has dimensions:', X4.shape)
print('X4 is an object of type:', type(X4))
print('The elements in X4 are of type:', X4.dtype)  

X4 has dimensions: (5, 5)
X4 is an object of type: <class 'numpy.ndarray'>
The elements in X4 are of type: float64


In [12]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
# similar to above but with each value defined individually
X5 = np.diag([10,20,30,50])

In [13]:
print('X5 = \n', X5)

X5 = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


numpy.arange
Syntax:

numpy.arange([start, ]stop, [step, ]dtype=None)

It returns evenly spaced values within a given interval. Details about the optional arguments are available in documentation.

NumPy also allows you to create ndarrays that have evenly spaced values within a given interval. NumPy's np.arange() function is very versatile and can be used with either one, two, or three arguments. Below we will see examples of each case and how they are used to create different kinds of ndarrays.

Let's start by using np.arange() with only one argument. When used with only one argument, np.arange(N) will create a rank 1 ndarray with consecutive integers between 0 and N - 1. Therefore, notice that if I want an array to have integers between 0 and 9, I have to use N = 10, NOT N = 9, as in the example below:

Example: Create a Numpy array of evenly spaced values in a given range, using arange(stop_val)

In [17]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
X6 = np.arange(10)
# starts at zero
# goes up to buy not including (exlusive)

In [18]:
print('X6 = ', X6)


X6 =  [0 1 2 3 4 5 6 7 8 9]


In [19]:
print('X6 has dimensions:', X6.shape)
print('X6 is an object of type:', type(X6))
print('The elements in X6 are of type:', X6.dtype)

X6 has dimensions: (10,)
X6 is an object of type: <class 'numpy.ndarray'>
The elements in X6 are of type: int64


When used with two arguments, np.arange(start,stop) will create a rank 1 ndarray with evenly spaced values within the half-open interval [start, stop). This means the evenly spaced numbers will include start but exclude stop. Let's see an example

Example 6. Create a Numpy array using arange(start_val, stop_val)

In [20]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9.
X7 = np.arange(4,10)

In [21]:
print('X7 = ', X7)

X7 =  [4 5 6 7 8 9]


In [22]:
print('X7 has dimensions:', X7.shape)
print('X7 is an object of type:', type(X7))
print('The elements in X7 are of type:', X7.dtype)

X7 has dimensions: (6,)
X7 is an object of type: <class 'numpy.ndarray'>
The elements in X7 are of type: int64


As we can see, the function np.arange(4,10) generates a sequence of integers with 4 inclusive and 10 exclusive.

Finally, when used with three arguments, np.arange(start,stop,step) will create a rank 1 ndarray with evenly spaced values within the half-open interval [start, stop) with step being the distance between two adjacent values. Let's see an example:



Example . Create a Numpy array using arange(start_val, stop_val, step_size)

In [26]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
X8 = np.arange(1,14,3)

In [27]:
print('X8 = ', X8)

X8 =  [ 1  4  7 10 13]


In [28]:
print('X8 has dimensions:', X8.shape)
print('X8 is an object of type:', type(X8))
print('The elements in X8 are of type:', X8.dtype) 

X8 has dimensions: (5,)
X8 is an object of type: <class 'numpy.ndarray'>
The elements in X8 are of type: int64


We can see that x has sequential integers between 1 and 13 but the difference between all adjacent values is 3.

numpy.linspace
SYNTAX:

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

It returns num evenly spaced values calculated over the interval [start, stop]. Details about the optional arguments are available here.

Even though the np.arange() function allows for non-integer steps, such as 0.3, the output is usually inconsistent, due to the finite floating point precision. For this reason, in the cases where non-integer steps are required, it is usually better to use the function np.linspace(). The np.linspace(start, stop, N) function returns N evenly spaced numbers over the closed interval [start, stop]. This means that both the start and thestop values are included. We should also note the np.linspace() function needs to be called with at least two arguments in the form np.linspace(start,stop). In this case, the default number of elements in the specified interval will be N= 50. The reason np.linspace() works better than the np.arange() function, is that np.linspace() uses the number of elements we want in a particular interval, instead of the step between values. Let's see some examples:

Example: Create a Numpy array using linspace(start, stop, n), with stop inclusive.

In [29]:
X9 = np.linspace(0,25,10)
#STOP ELEMENT (25) IS NATURALLY INCLUSIVE.
#MUST BE SET TO FALSE 'endpoint = False' TO BE EXCLUSIVE. 

In [30]:
print('X9 = \n', X9)

X9 = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [31]:
print('X9 has dimensions:', X9.shape)
print('X9 is an object of type:', type(X9))
print('The elements in X9 are of type:', X9.dtype) 

X9 has dimensions: (10,)
X9 is an object of type: <class 'numpy.ndarray'>
The elements in X9 are of type: float64


As we can see from the above example, the function np.linspace(0,25,10) returns an ndarray with 10 evenly spaced numbers in the closed interval [0, 25]. We can also see that both the start and end points, 0 and 25 in this case, are included. However, you can let the endpoint of the interval be excluded (just like in the np.arange() function) by setting the keyword endpoint = False in the np.linspace() function. Let's create the same x ndarray we created above but now with the endpoint excluded:

Example: Create a Numpy array using linspace(start, stop, n), with stop excluded.

In [34]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.
X10 = np.linspace(0,25,10, endpoint = False)

In [35]:
print('X10 = ', X10)

X10 =  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [36]:
print('X10 has dimensions:', X10.shape)
print('X10 is an object of type:', type(X10))
print('The elements in X10 are of type:', X10.dtype) 

X10 has dimensions: (10,)
X10 is an object of type: <class 'numpy.ndarray'>
The elements in X10 are of type: float64


As we can see, because we have excluded the endpoint, the spacing between values had to change in order to fit 10 evenly spaced numbers in the given interval.

numpy.reshape - This is a Function.
Syntax:

numpy.reshape(array, newshape, order='C')[source]
It gives a new shape to an array without changing its data. More details about the arguments are available here.

So far, we have only used the built-in functions np.arange() and np.linspace() to create rank 1 ndarrays. However, we can use these functions to create rank 2 ndarrays of any shape by combining them with the np.reshape() function. The np.reshape(ndarray, new_shape) function converts the given ndarray into the specified new_shape. It is important to note that the new_shape should be compatible with the number of elements in the given ndarray. For example, you can convert a rank 1 ndarray with 6 elements, into a 3 x 2 rank 2 ndarray, or a 2 x 3 rank 2 ndarray, since both of these rank 2 arrays will have a total of 6 elements. However, you can't reshape the rank 1 ndarray with 6 elements into a 3 x 3 rank 2 ndarray, since this rank 2 array will have 9 elements, which is greater than the number of elements in the original ndarray. Let's see some examples:

Example: Create a Numpy array by feeding the output of arange() function as an argument to the reshape() function.

In [37]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
X11 = np.arange(20)

In [38]:
print('Original X11 = ', X11)

Original X11 =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [42]:
# We reshape x into a 4 x 5 ndarray
#this is a function
X11 = np.reshape(X11, (4,5))

In [43]:
print('Reshaped X11 = \n', X11)

Reshaped X11 = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [44]:
print('X11 has dimensions:', X11.shape)
print('X11 is an object of type:', type(X11))
print('The elements in X11 are of type:', X11.dtype) 

X11 has dimensions: (4, 5)
X11 is an object of type: <class 'numpy.ndarray'>
The elements in X11 are of type: int64


numpy.ndarray.reshape - This one is a Method.
Syntax:

ndarray.reshape(shape, order='C')
It returns an array containing the same data with a new shape. 

Need clarity between a Method versus Function? - Refer to StackOverflow
One great feature about NumPy, is that some functions can also be applied as methods. This allows us to apply different functions in sequence in just one line of code. ndarray methods are similar to ndarray attributes in that they are both applied using dot notation (.). Let's see how we can accomplish the same result as in the above example, but in just one line of code:

In [45]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
####
#i.this is a method
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

In [46]:
print('Y = \n', Y)

Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [47]:
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


As we can see, we get the exact same result as before. Notice that when we use reshape() as a method, it's applied as ndarray.reshape(new_shape). This converts the ndarray into the specified shape new_shape. As before, it is important to note that the new_shape should be compatible with the number of elements in ndarray. In the example above, the function np.arange(20) creates an ndarray and serves as the ndarray to be reshaped by the reshape() method. Therefore, when using reshape() as a method, we don't need to pass the ndarray as an argument to the reshape() function, instead we only need to pass the new_shape argument.

In the same manner, we can also combine reshape() with np.linspace() to create rank 2 arrays, as shown in the next example.



Example: Create a rank 2 Numpy array by using the reshape() function.

In [48]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X12 = np.linspace(0,50,10, endpoint=False).reshape(5,2)

In [49]:
print('X12 = \n', X12)

X12 = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [50]:
print('X12 has dimensions:', X12.shape)
print('X12 is an object of type:', type(X12))
print('The elements in X12 are of type:', X12.dtype)

X12 has dimensions: (5, 2)
X12 is an object of type: <class 'numpy.ndarray'>
The elements in X12 are of type: float64


The last type of ndarrays we are going to create are random ndarrays. Random ndarrays are arrays that contain random numbers. Often in Machine Learning, you need to create random matrices, for example, when initializing the weights of a Neural Network. NumPy offers a variety of random functions to help us create random ndarrays of any shape.

Let's start by using the np.random.random(shape) function to create an ndarray of the given shape with random floats in the half-open interval [0.0, 1.0).

Example: Create a Numpy array using the numpy.random.random() function.

In [51]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X13 = np.random.random((3,3))

In [52]:
print('X13 = \n', X13)

X13 = 
 [[0.78864844 0.42717795 0.09170745]
 [0.73381584 0.99519463 0.46795495]
 [0.89864433 0.88449479 0.79336817]]


In [53]:
print('X13 has dimensions:', X13.shape)
print('X13 is an object of type:', type(X13))
print('The elements in X13 are of type:', X13.dtype)

X13 has dimensions: (3, 3)
X13 is an object of type: <class 'numpy.ndarray'>
The elements in X13 are of type: float64


NumPy also allows us to create ndarrays with random integers within a particular interval. The function np.random.randint(start, stop, size = shape) creates an ndarray of the given shape with random integers in the half-open interval [start, stop). Let's see an example:

Example: Create a Numpy array using the numpy.random.randint() function.

In [54]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X14 = np.random.randint(4,15,size=(3,2))

In [55]:
print('X14 = \n', X14)

X14 = 
 [[ 4 11]
 [13  4]
 [ 5 11]]


In [56]:
print('X14 has dimensions:', X14.shape)
print('X14 is an object of type:', type(X14))
print('The elements in X14 are of type:', X14.dtype)

X14 has dimensions: (3, 2)
X14 is an object of type: <class 'numpy.ndarray'>
The elements in X14 are of type: int64


In some cases, you may need to create ndarrays with random numbers that satisfy certain statistical properties. For example, you may want the random numbers in the ndarray to have an average of 0. NumPy allows you create random ndarrays with numbers drawn from various probability distributions. The function np.random.normal(mean, standard deviation, size=shape), for example, creates an ndarray with the given shape that contains random numbers picked from a normal (Gaussian) distribution with the given mean and standard deviation. Let's create a 1,000 x 1,000 ndarray of random floating point numbers drawn from a normal distribution with a mean (average) of zero and a standard deviation of 0.1.

Example: Create a Numpy array of "Normal" distributed random numbers, using the numpy.random.normal() function.

In [57]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X15 = np.random.normal(0, 0.1, size=(1000,1000))

In [58]:
print('X15 = \n', X15)

X15 = 
 [[ 0.03855639  0.13127246 -0.08095667 ...  0.03145241 -0.1411756
  -0.2455123 ]
 [-0.00185908  0.0364639  -0.11275755 ... -0.0705952  -0.16133063
   0.00697536]
 [-0.000606   -0.00144366  0.03397868 ...  0.35176108  0.04274616
  -0.06206533]
 ...
 [ 0.0225916  -0.1086377   0.13242427 ...  0.11233289  0.21732402
   0.04411066]
 [ 0.09144309 -0.1201856   0.03289308 ... -0.1301018   0.07526587
   0.03864622]
 [ 0.01257458  0.09120699  0.04213181 ... -0.03207131  0.06002964
  -0.21130642]]


In [59]:
print('X15 has dimensions:', X15.shape)
print('X15 is an object of type:', type(X15))
print('The elements in X15 are of type:', X15.dtype)
print('The elements in X15 have a mean of:', X15.mean())
print('The maximum value in X15 is:', X15.max())
print('The minimum value in X15 is:', X15.min())
print('X15 has', (X15 < 0).sum(), 'negative numbers')
print('X15 has', (X15 > 0).sum(), 'positive numbers')


X15 has dimensions: (1000, 1000)
X15 is an object of type: <class 'numpy.ndarray'>
The elements in X15 are of type: float64
The elements in X15 have a mean of: 9.290059226213932e-05
The maximum value in X15 is: 0.49089961925711756
The minimum value in X15 is: -0.4652841241908705
X15 has 499574 negative numbers
X15 has 500426 positive numbers


As we can see, the average of the random numbers in the ndarray is close to zero, both the maximum and minimum values in X are symmetric about zero (the average), and we have about the same amount of positive and negative numbers.
Additional Resource
Refer to more examples available at NumPy.org - Array creation